.PHONY: clean
.PHONE: nuke

all: myProg.java BasicNum.java ZeroException.java CheckGCD.java
	clear
	javac myProg.java BasicNum.java ZeroException.java CheckGCD.java
	
	clear
	
	java myProg


clean:
	rm *.class -f 

nuke:
	rm *.class *.java -f